/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/Volunteer'
import { Route as UpcomingProjectsRouteImport } from './routes/UpcomingProjects'
import { Route as TermsAndConditionsRouteImport } from './routes/TermsAndConditions'
import { Route as SkillProgramsRouteImport } from './routes/SkillPrograms'
import { Route as PrivacyPolicyRouteImport } from './routes/PrivacyPolicy'
import { Route as PartnerWithUsRouteImport } from './routes/PartnerWithUs'
import { Route as MembersRouteImport } from './routes/Members'
import { Route as MediaRouteImport } from './routes/Media'
import { Route as LearningHubRouteImport } from './routes/LearningHub'
import { Route as JourneyRouteImport } from './routes/Journey'
import { Route as ImpactRouteImport } from './routes/Impact'
import { Route as DonateAndSupportRouteImport } from './routes/DonateAndSupport'
import { Route as DonateRouteImport } from './routes/Donate'
import { Route as CookiePolicyRouteImport } from './routes/CookiePolicy'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as CampaignRouteImport } from './routes/Campaign'
import { Route as BlogRouteImport } from './routes/Blog'
import { Route as AboutRouteImport } from './routes/About'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/Volunteer',
  path: '/Volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingProjectsRoute = UpcomingProjectsRouteImport.update({
  id: '/UpcomingProjects',
  path: '/UpcomingProjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/TermsAndConditions',
  path: '/TermsAndConditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillProgramsRoute = SkillProgramsRouteImport.update({
  id: '/SkillPrograms',
  path: '/SkillPrograms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/PrivacyPolicy',
  path: '/PrivacyPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/PartnerWithUs',
  path: '/PartnerWithUs',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/Members',
  path: '/Members',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/Media',
  path: '/Media',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/LearningHub',
  path: '/LearningHub',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/Journey',
  path: '/Journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/Impact',
  path: '/Impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateAndSupportRoute = DonateAndSupportRouteImport.update({
  id: '/DonateAndSupport',
  path: '/DonateAndSupport',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/Donate',
  path: '/Donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/CookiePolicy',
  path: '/CookiePolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/Campaign',
  path: '/Campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/Blog',
  path: '/Blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Blog': typeof BlogRoute
  '/Campaign': typeof CampaignRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/Impact': typeof ImpactRoute
  '/Journey': typeof JourneyRoute
  '/LearningHub': typeof LearningHubRoute
  '/Media': typeof MediaRoute
  '/Members': typeof MembersRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/Volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/About'
    | '/Blog'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/Media'
    | '/Members'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/SkillPrograms'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/About'
    | '/Blog'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/Media'
    | '/Members'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/SkillPrograms'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Volunteer'
  id:
    | '__root__'
    | '/'
    | '/About'
    | '/Blog'
    | '/Campaign'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/Impact'
    | '/Journey'
    | '/LearningHub'
    | '/Media'
    | '/Members'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/SkillPrograms'
    | '/TermsAndConditions'
    | '/UpcomingProjects'
    | '/Volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CampaignRoute: typeof CampaignRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DonateRoute: typeof DonateRoute
  DonateAndSupportRoute: typeof DonateAndSupportRoute
  ImpactRoute: typeof ImpactRoute
  JourneyRoute: typeof JourneyRoute
  LearningHubRoute: typeof LearningHubRoute
  MediaRoute: typeof MediaRoute
  MembersRoute: typeof MembersRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SkillProgramsRoute: typeof SkillProgramsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UpcomingProjectsRoute: typeof UpcomingProjectsRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Volunteer': {
      id: '/Volunteer'
      path: '/Volunteer'
      fullPath: '/Volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UpcomingProjects': {
      id: '/UpcomingProjects'
      path: '/UpcomingProjects'
      fullPath: '/UpcomingProjects'
      preLoaderRoute: typeof UpcomingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsAndConditions': {
      id: '/TermsAndConditions'
      path: '/TermsAndConditions'
      fullPath: '/TermsAndConditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SkillPrograms': {
      id: '/SkillPrograms'
      path: '/SkillPrograms'
      fullPath: '/SkillPrograms'
      preLoaderRoute: typeof SkillProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PrivacyPolicy': {
      id: '/PrivacyPolicy'
      path: '/PrivacyPolicy'
      fullPath: '/PrivacyPolicy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PartnerWithUs': {
      id: '/PartnerWithUs'
      path: '/PartnerWithUs'
      fullPath: '/PartnerWithUs'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Members': {
      id: '/Members'
      path: '/Members'
      fullPath: '/Members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Media': {
      id: '/Media'
      path: '/Media'
      fullPath: '/Media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub': {
      id: '/LearningHub'
      path: '/LearningHub'
      fullPath: '/LearningHub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Journey': {
      id: '/Journey'
      path: '/Journey'
      fullPath: '/Journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Impact': {
      id: '/Impact'
      path: '/Impact'
      fullPath: '/Impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DonateAndSupport': {
      id: '/DonateAndSupport'
      path: '/DonateAndSupport'
      fullPath: '/DonateAndSupport'
      preLoaderRoute: typeof DonateAndSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Donate': {
      id: '/Donate'
      path: '/Donate'
      fullPath: '/Donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CookiePolicy': {
      id: '/CookiePolicy'
      path: '/CookiePolicy'
      fullPath: '/CookiePolicy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaign': {
      id: '/Campaign'
      path: '/Campaign'
      fullPath: '/Campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Blog': {
      id: '/Blog'
      path: '/Blog'
      fullPath: '/Blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CampaignRoute: CampaignRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DonateRoute: DonateRoute,
  DonateAndSupportRoute: DonateAndSupportRoute,
  ImpactRoute: ImpactRoute,
  JourneyRoute: JourneyRoute,
  LearningHubRoute: LearningHubRoute,
  MediaRoute: MediaRoute,
  MembersRoute: MembersRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SkillProgramsRoute: SkillProgramsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UpcomingProjectsRoute: UpcomingProjectsRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
